### PR TITLE
switch: show profile selector on X button in main menu

### PR DESCRIPTION
**Pull request by terabyte25**

### CODE REVIEW

**Comment by fgsfdsfgs** [comment]
That's not gonna work. Username is read once at the start of the game. Gotta call the applet in Switch::init or something. Or make it also call readUser.

**Comment by terabyte25** [comment]
https://github.com/OpenMW/openmw/blob/master/components/files/fixedpath.hpp saves the paths as a variable, guess I'll have to add a function to refresh.

**Comment by fgsfdsfgs** [comment]
Or you could let the player select their account once at the start like most Switch games do.

**Comment by terabyte25** [comment]
@fgsfdsfgs Because I've been playing Skyrim so much recently, and because on the switch you have the option to change the user while in the main menu, I made it similar to the Skyrim's mechanics, with the same manner of switching users.

**Comment by fgsfdsfgs** [comment]
I tried it, and it seems that if you call the user select applet this way, it asks you to log into Nintendo online shit for some reason.

**Comment by fgsfdsfgs** [comment]
[Checkpoint's](https://github.com/FlagBrew/Checkpoint/blob/master/switch/source/account.cpp#L113) implementation seems to work. Going to use that for now, but I don't know whether it works on all FW versions (or at least >= 3.0.0).

**Pull request closed without merging**
